#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("AndroidTest.Resource", IsApplication=true)]

namespace AndroidTest
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f04000c
			public const int API_KEY_Input = 2130968588;
			
			// aapt resource value: 0x7f04000b
			public const int Device_ID_Input = 2130968587;
			
			// aapt resource value: 0x7f04000f
			public const int ED_ShowDialog = 2130968591;
			
			// aapt resource value: 0x7f040010
			public const int ET_ShowDialog = 2130968592;
			
			// aapt resource value: 0x7f04000d
			public const int SD_ShowDialog = 2130968589;
			
			// aapt resource value: 0x7f04000e
			public const int ST_ShowDialog = 2130968590;
			
			// aapt resource value: 0x7f040011
			public const int SaveBtn = 2130968593;
			
			// aapt resource value: 0x7f040012
			public const int SaveTip = 2130968594;
			
			// aapt resource value: 0x7f040002
			public const int UpdateButton = 2130968578;
			
			// aapt resource value: 0x7f040000
			public const int UpdateScrollView = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int UpdateText = 2130968577;
			
			// aapt resource value: 0x7f040009
			public const int div_tab_bar = 2130968585;
			
			// aapt resource value: 0x7f04000a
			public const int fragment_container = 2130968586;
			
			// aapt resource value: 0x7f040005
			public const int tab_menu = 2130968581;
			
			// aapt resource value: 0x7f040003
			public const int tab_title = 2130968579;
			
			// aapt resource value: 0x7f040006
			public const int txt_deal = 2130968582;
			
			// aapt resource value: 0x7f040008
			public const int txt_setting = 2130968584;
			
			// aapt resource value: 0x7f040004
			public const int txt_top = 2130968580;
			
			// aapt resource value: 0x7f040007
			public const int txt_user = 2130968583;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f020000
			public const int Display = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Main = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Setting = 2130837506;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f030002
			public const int Api_Key = 2130903042;
			
			// aapt resource value: 0x7f030001
			public const int Device_ID = 2130903041;
			
			// aapt resource value: 0x7f030005
			public const int EndDate = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int EndTime = 2130903046;
			
			// aapt resource value: 0x7f030003
			public const int StartDate = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int StartTime = 2130903044;
			
			// aapt resource value: 0x7f030000
			public const int app_name = 2130903040;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
